### ISSUE TITLE
HMRC-RTS-Small-area

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#16]
Jenkins has failed and shows two errors:

Count of Business 
GBP total 

have not been pathified which appears to be causing the fail so passing this back

**Comment by ajtucker** [comment]
- [ ] Output metadata to `observations.csv-metadata.trig`

**Comment by Grace-W** [comment]
QA notes:

Name: Regional trade in goods statistics disaggregated by smaller geographical areas: 2018

Dataset viewable
Shows in the main search list
Shows dataset when clicked on
Need a way to capture all metadata in notes tab

Does data match?
ALL NUTS1 AREAS: Matches - From tab 1, not transformed regional NUTS data
NUTS - table 2 EU/Non EU accurate (TST NUTS2 tab)
WM BTTA - NE BTTA etc- BTTA =below threshold traders

Distinction between east/west removed - ie Cumbria

Red screen 500 error when filtering for:
T3 NUTS3 - all product type Cumbria, EU/Non EU and clicking on see more rows for another filter

NUTS1 location regions taken out

Differences in column/row headers:
SITC codes have been changed to reflect type:
0 Food & live animals
1 Beverages & tobacco
2 Crude materials, inedible, except fuels
3 Mineral fuels, lubricants & related materials
4 Animal & vegetable oils, fats & waxes
5 Chemicals & related products
6 Manufactured goods classified chiefly by material
7 Machinery & transport equipment
8 Miscellaneous manufactured articles
9 Commodities/transactions not classified elsewhere

Downloading csv with and without filters - only comes up with one row of data

Observation status column twice in PMD - what is it?

**Comment by IeuanMan** [comment]
@david-hull 

https://docs.google.com/document/d/1GDqqVtWmHHOAtPA9t27NM8Wu9Yd6pDJv_ehR2osG7KY/edit#

BA Quality Assurance High Level Checks 
Dataset: Regional trade in goods statistics disaggregated by smaller geographical areas: 2018
Done by: D Hull
Date: 3/4/20

PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
No
Does transformed info seem to match the original?
Yes
Contents Modified Date
2020-03-10
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
No
Modified Date
26 Mar 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
Yes
Does the structure look sensible?
Yes

Overview
General comments on the dataset

Currently release is 2018 but normally wouldn’t expect a date in the title i.e. 2018, rather a generic title to enable future updates.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

There is no metadata available. Short title listed in “about” but doesn’t appear in “explore cube” or main PMD page. No landing page or other info, etc.
Metadata is present in airtable.

Dataset on the home landing page called “UK regional trade in goods statistics disaggregated by smaller geographical areas” which to me is a slightly better title.
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Overall column titles and items look sensible and do seem to match original data.
Having “NUTS” dimensions looks a bit odd to me.
“Product” dimension in the original XLS spreadsheet I assume taken from “SITC”..
There is no filter available for “Trade Reporter Geography” or “Product”.
“Observation” column is not required to be seen.

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

Overall, data seems consistent, to scale and looks sensible.

There will never be a figure in both “GBP total” and “Count of Business” in PMDv4 because of the way “unit of measure” is set-up, looks a bit odd to me - just from a user point of view. Perhaps the only way round this would have been to split the dataset, which may not be ideal?

**Comment by VTula2000** [comment]
- [ ] No metadata available
- Metadata scraped from Landing page of source data, So PMD3 displayed meta data as according to source data

- [ ] Filter issues
- filter issues raised with swirrl https://github.com/Swirrl/ons-data-export/issues/25

- [ ] Variations in Dimension titles PMD3 vs PMDv4
- Raised with swirrl https://github.com/Swirrl/ons-data-export/issues/25

- [ ] Structure of data
- multiple Observations and Unit of measure in a single row format is to match original source data

**Comment by ajtucker** [comment]
On the metadata issue, I've got a fix going through for GSS-Cogs/gss-utils#46, pending a fix for GSS-Cogs/gss-utils#47.

**Comment by ajtucker** [comment]
@david-hull, the "description" for this dataset and other's that are published on gov.uk was blank and I've now updated things to fix this and have re-run the pipeline; can you check http://gss-data.org.uk/dataset?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-rts-small-area ?

The title for the dataset is literally as given by the publisher -- the title on the landing page without the year is the title of the collection, not of the dataset. While I agree that we shouldn't be putting e.g. year in the title, this has got to be raised with the publisher as I don't think it's our place to make this kind of change, what do you think? /cc @RobThomlinson 

Still to do:

- [ ] sort out the labels for the dimensions
- [ ] reload in PMD4 and check
- [ ] track the feature/issue in PMD4 for rolling up multiple measures.
- [ ] enable overriding metadata GSS-Cogs/gss-utils#38

**Comment by JasonHowell** [comment]
BA comments "Regional trade in goods statistics disaggregated by smaller geographical areas: 2018 has no description, but then the landing page doesn't either.  The title is good enough anyway (but with the outstanding "should it have the 2018" issue)"  Hence okay to go in it's current state.

**Comment by MartynBSpooner** [comment]
Issue raised by Swirl - labels to be assigned correctly.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by Grace-W** [comment]
Note for the DE - please can you change 'GBP total' to 'GBP Million' as the latter is what is used in the original dataset. Thanks

**Comment by canwaf** [comment]
This dataset is likely redundant with respects to newly surfaced RTS values (Issue #12) having reviewed the output.

**Comment by canwaf** [comment]
Update: the granularity of source of trade in the UK is not present in RTS as it is in RTS-small area.

**Comment by canwaf** [comment]
A Data Manager is required to update `info.json` with column mapping.

**Comment by mikeAdamss** [comment]
so I think the bugged bit is cleared up, we're as far as tests complaining about not having a value for every declared measures and some stuff around geographies so moving this back over.

this was build with the cubes multi-measures hack, so if that's an issue or we need it any other DE thingies let me know, don't want to ping pong this back and fore.

**Comment by ajtucker** [comment]
I've merged this back into a single CSV using the multi-measure "types" declaration in the `info.json`.

The checks are now failing because there are some missing values in both of the geography columns (blank values in the CSV). Needs a DE to check for missing/empty values.

It also look as though we might have some geography values that don't appear in the HMRC geographies codelist. May need a DM to check these.

**Comment by AndrewtGSScogs** [comment]
I have updated the codelist to match take into account the missing values

**Comment by mikeAdamss** [comment]
there's two issues on this that I can see:

1.) missing values for `Nuts Geography` as per comment form Alex.
2.) The year has been hardcoded to 2018, the data is now for 2019.

Whole thing needs a bit of a shake up tbh.

@canwaf - you mentioned maybe picking this up, you want it or shall I do it? (don't care, but you mentioned it in standup)

**Comment by canwaf** [comment]
I'm good @mikeAdamss. You're welcome to it.

**Comment by mikeAdamss** [comment]
fixed the date thing, the geography problem is because we're pulling in the nuts codelist and using that to lookup the codes for the nuts geography labels present in the source data.

the failure is we don't have a label/code combination for `Na h-Eileanan Siar` in the codelist, which is resulting in translating it as a nan/blank (from tab T3 of the source data).

I've pointed it at https://github.com/GSS-Cogs/family-trade/blob/master/reference/codelists/nuts-geographies.csv, so if we add the missing area there I _think_ it'll work (hard to be 100% certain, there's a lot of old ropey code in play in this).

**Comment by AndrewtGSScogs** [comment]
Thanks @mikeAdamss ill look at this today! thought i fixed the codelist issues.. hopefully this will get it over the line! Thanks again

**Comment by AndrewtGSScogs** [comment]
I have updated the nuts geographies codelist to get this onto to PMD4 there was a difference in naming conventions for ukm64 i have updated to match the current wording used in small areas. Sparql tests are still failing on missing data from codelists. Investigating ONS-partner geographies to find solution for missing codes

**Comment by LPerryman** [comment]
Found some errors in data and corrected what i could but would be good to start this one from scratch .
Lots of notes in spreadsheet, have added most to the scraper description
Data published as 2 datasets, Business Count and GBP Million.
Have add codelist URIs in info.json just to get the filters working, using dimension instead of parent causes a 500 error on PMD4.

**Comment by LPerryman** [comment]
Business Count
https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-rts-small-area%2Fhmrc-rts-small-area-business-count-catalog-entry&filters-drawer=open

£ Million
https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fhmrc-rts-small-area%2Fhmrc-rts-small-area-gbp-million-catalog-entry&filters-drawer=open

**Comment by Robsteranium** [comment]
The SITC 4 dimension doesn't have a codelist.

I'd also suggest we remove "2019" from the title/ URI in anticipation of further year's of data.
