### ISSUE TITLE
ONS-International-Trade-in-Services

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/family-trade#4]

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-UK-trade-in-goods-by-industry-country-and-commodity/40/)

Blocks #3

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS_CPA/72/)

Blocks #18

**Comment by ajtucker** [comment]
- [ ] Output metadata to `observations.csv-metadata.trig`
- [ ] Create CSVWMetadata from local repo: `CSVWMetadata('https://gss-cogs.github.io/family-trade/reference/')`

**Comment by ajtucker** [comment]
Jenkins job result: FAILURE
Stage: Upload Tidy Data
[View full output](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-FDI/94/)

Blocks #26

**Comment by ajtucker** [comment]
Build was fixed!

**Comment by Shannon95** [comment]
- [ ] Does the dataset show up or is there an error?
- [ ] Is it in the list of datasets from the main page?
- [ ] Is there descriptive metadata on the search page?
- [ ] Does transformed info match the original?
- [ ] Does the tidydata download show all the data?
- [ ] Note differences in column/row headers
- [ ] Are there multiple cubes? List titles of cubes
- [ ] What needs differentiating? Totals
- [ ] Are there titles that need harmonising? World/Worldwide
- [ ] Does the structure look sensible?
- [ ] Does the hierarchy work?
- [ ] What needs further investigation or context?
- [ ] Any duplications?
- [ ] List any detailed metadata/methodology to add retrospectively
- [ ] Short metadata added

**Comment by IeuanMan** [comment]
@david-hull 

https://docs.google.com/document/d/1FKaMM_cg0oFF5FQSGRm1fSUO0YAIYU-6w8DV2EFoCXc/edit#heading=h.7783s8wimep8

BA Quality Assurance High Level Checks 
Dataset: International trade in services
Done by: David Hull
Date: 6-4-20
PMD V4
Is the dataset listed  in PMD v4 staging?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v4 staging landing page?
Yes but no overview
Does transformed info seem to match the original?
Yes
Contents Modified Date
2020-03-10
PMD V3
Is the dataset listed  in PMD V3?
Yes
Does the dataset open?
Yes
Is there descriptive metadata on the PMD v3 landing page?
Yes
Modified Date
3 Apr 2020
General
Is the dataset title meaningful?
Yes
Do the filters work & look sensible?
Yes
Does the structure look sensible?
Yes

Overview
General comments on the dataset

Latest release is 2018.
Dataset seems to be well transformed from a data point of view (though with some issues noted below), however the metadata has no overview nor specific contact details.
Metadata
Is the Title, Publisher, Contact, Date Issued, description consistent with the source data

Metadata is available but there is no overview description in the “about” page.
Metadata is present in airtable.
Only a generic contact email addresses is noted in “about” but a more detailed specific contact is present in airtable and the landing page.
No link available to the original website landing page.
Dimensions
Do the column titles look sensible? Do the items look sensible? Does it match the original data?

Overall column titles and items look sensible and do seem to match original data ,however ,I think the column “Observation Status” could be able to be hidden.
No filter available on “Product” or “measure type”, though “measure type” seems to only consist of “GBP Total” - if so, of course this would negate the need for a filter. Looks odd to me to have a “GBP Total” column of it’s own with “GBP total” the main (if not only) entry in the “measure type”.
The data presented in the “GBP Total” column seems inconsistent with a mixture of whole numbers and others to many decimal points.

Observations
Is the PMD data consistent with the source data? Number of significant figures appropriate? Do they look sensible?

Overall, data seems consistent and looks sensible, however, as noted above scaling looks off and “GBP Total”

**Comment by ajtucker** [comment]
Reopening - Jenkins was closing these when the pipeline succeeded.

**Comment by Shannon95** [comment]
BA/DE Review Summary of aspects to consider / fix 

**Comments on what a user can see via PMDv4** 
- Metadata has no overview nor specific contact details, which is present on airtable. 
- No link available to the original website landing page.
- BA comment suggesting that the column Observation Status be hidden. However this represents the Marker and is of importance to a user when there is no value for an observation. 
- Some of the filters are either not available for certain dimensions or not working as expected. (No filter available on “Product” or “measure type”)

**Technical comments / aspects that can be fixed via transformation code.** 
- [ ] The data presented in the “GBP Total” column seems inconsistent with a mixture of whole numbers and others to many decimal points.
This has now been fixed and rounding to two decimal places.

**Comment by Shannon95** [comment]
Moving to _**Needs Sign Off**_ as the only issues remaining are that associated with the PMDv4 side.

**Comment by JasonHowell** [comment]
BA's have confirmed it is good to go in its current state.

**Comment by JasonHowell** [comment]
Closing issue as now been deployed onto PMDv4.

**Comment by ajtucker** [comment]
Hey @mikeAdamss , this one seems to be having problems grabbing distribution metadata. The [console](https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ONS-International-Trade-in-Services/132/console) mentions issues with versions, but this could be a red herring as when I run it locally I just don't get any distributions.

**Comment by mikeAdamss** [comment]
couldn't replicate this either but there is a scenario where it could happen so added a catch. Will try it when the latest ONS scraper is in.

**Comment by mikeAdamss** [comment]
working with the newest gssutils build, moving it over.

**Comment by rossbowen** [comment]
Could `itis-industry` and `itis-service` be mapped to the relevant SIC code and renamed `SIC Section` and `SIC Subsection`. Leave concepts like `all` as is for now.

https://github.com/GSS-Cogs/family-trade/blob/master/reference/codelists/standard-industrial-classification-2007.csv

**Comment by Shannon95** [comment]
Going back to the producer regarding if we are using SIC codes or not. Blocked for now.

**Comment by Shannon95** [comment]
Ready for review here: https://staging.gss-data.org.uk/cube/explore?uri=http%3A%2F%2Fgss-data.org.uk%2Fdata%2Fgss_data%2Ftrade%2Fons-international-trade-in-services-catalog-entry&apply-filters=true
